### ISSUE TITLE
Question about  actor_mask in Predictor network

### ISSUE THREAD

**Issue by invinciblenuonuo** [MCZhi/DIPP#35]
The actor_mask is generate by：
`actor_mask = torch.eq(torch.cat([ego.unsqueeze(1), neighbors[..., :-1]], dim=1), 0)[:, :, -1, -1]`
It means concatenating the feature tensors of ego and neighbors, comparing each element with 0, setting elements equal to 0 to True, and then taking the last feature of the last timestep of each agent as the mask.

My question is, as far as I know, the last feature of the last dimension of an agent represents its height. Why can the height feature of the last timestep be used as a criterion for masking?
feature:
`ego_state = np.array([sdc_state.center_x, sdc_state.center_y, sdc_state.heading, sdc_state.velocity_x, sdc_state.velocity_y, sdc_state.length, sdc_state.width, sdc_state.height])`

**Comment by leleovo-hub** [comment]
when I run data_process.py,file, an unexpected error occurred:(DIPP) root@autodl-container-4f654a8570-6fc6b9a6:/tmp/pycharm_project_254# python data_process.py --load_path /tmp/pycharm_project_254/data/train --save_path /tmp/pycharm_project_254/newdata/train
2024-12-25 00:50:03.555570: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-25 00:50:03.612737: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Processing uncompressed_scenario_training_20s_training_20s.tfrecord-00000-of-01000: 0%| | 0/75 [00:00<?, ?it/s]Traceback (most recent call last):
 File "data_process.py", line 444, in <module>
 processor.process_data(save_path, viz=False)
 File "data_process.py", line 392, in process_data
 self.build_map(parsed_data.map_features, parsed_data.dynamic_map_states)
 File "data_process.py", line 38, in build_map
 map = getattr(map, map_type)
TypeError: getattr(): attribute name must be string.

It indicates that map_type is not a string.how to sovle it
